version: '3.7'
services:
  # application
  micro-application:
    container_name: microservice_application
    restart: 'unless-stopped'
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
    ports:
      - ${APPLICATION_PORT}:8080
    networks:
      - microservice-network
    volumes:
      - './:/var/www/api'
  # DataBase
  postgres:
    container_name: microservice_postgres
    restart: 'unless-stopped'
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/postgres/
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
